/*
 * File: app/model/PersonAccount.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.accounts.model.PersonAccount', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'personCode'
        },
        {
            name: 'name'
        },
        {
            name: 'dept'
        },
        {
            name: 'duty'
        },
        {
            name: 'idCard'
        },
        {
            name: 'bank'
        },
        {
            name: 'bankAccount'
        },
        {
            name: 'bankOfDeposit'
        },
        {
            name: 'accountId'
        },
        {
            name: 'level'
        },
        {
            name: 'rank'
        },
        {
            name: 'note'
        },
        {
            name: 'accountItems'
        },
        {
            name: 'insuredPerson'
        }
    ]
});