/*
 * File: app/model/PersonSocialItem.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.model.PersonSocialItem', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'name'
        },
        {
            name: 'companyPaymentValue',
            type: 'float'
        },
        {
            name: 'personalPaymentValue',
            type: 'float'
        },
        {
            name: 'companyPaymentType'
        },
        {
            name: 'personalPaymentType'
        },
        {
            name: 'socialItemId'
        },
        {
            name: 'companyCardinality'
        },
        {
            name: 'personalCardinality'
        },
        {
            convert: function(v, rec) {
                if (v=='') {
                    if(rec.get('companyPaymentType') == 'Percent'){
                        v = rec.get('companyPaymentValue') * 100;
                    }else if(rec.get('companyPaymentType') == 'Quota'){
                        v = rec.get('companyPaymentValue');
                    }
                }
                return v;
            },
            name: 'displayCompanyPaymentValue'
        },
        {
            convert: function(v, rec) {
                if (v=='') {
                    if(rec.get('personalPaymentType') == 'Percent'){
                        v = rec.get('personalPaymentValue') * 100;
                    }else if(rec.get('personalPaymentType') == 'Quota'){
                        v = rec.get('personalPaymentValue');
                    }
                }
                return v;
            },
            name: 'displayPersonalPaymentValue'
        }
    ]
});