/*
 * File: app/model/SocialAccountItem.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.model.SocialAccountItem', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'socialItemId'
        },
        {
            name: 'name'
        },
        {
            name: 'companyPaymentType'
        },
        {
            name: 'personalPaymentType'
        },
        {
            name: 'companyPaymentValue',
            type: 'float'
        },
        {
            name: 'personalPaymentValue',
            type: 'float'
        },
        {
            name: 'id'
        },
        {
            name: 'carryType'
        },
        {
            name: 'precision',
            type: 'int'
        },
        {
            name: 'item'
        },
        {
            name: 'itemType'
        },
        {
            name: 'personalCardinality',
            type: 'float'
        },
        {
            name: 'companyCardinality',
            type: 'float'
        }
    ]
});