/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    paths: {
        'sion.salary.social': 'sion/salary/social/app'
    },
    models: [
        'SocialItem',
        'SocialItemType',
        'DecimalCarryType',
        'SocialAccount',
        'SocialAccountItem',
        'PaymentType',
        'PersonAccount',
        'InsuredPerson',
        'Level',
        'SalaryAccount',
        'Rank',
        'PersonSalaryItem',
        'PersonSocialItem',
        'InsuredPersonAccount'
    ],
    stores: [
        'SocialItem',
        'SocialItemType',
        'DecimalCarryType',
        'SocialAccount',
        'SocialAccountItem',
        'PaymentType',
        'PersonAccountStore',
        'LevelStore',
        'SalaryAccount',
        'RankStore',
        'PersonSalaryItem',
        'PersonSocialItem',
        'InsuredPersonAccount',
        'SocialAccountAll',
        'ChooseStore',
        'PersonAccountSearch'
    ],
    views: [
        'PersonAccountGrid',
        'UninsuredGrid',
        'PersonAccountForm',
        'InsuredSearchGrid',
        'SocialItemGrid',
        'SocialItemForm',
        'SocialAccountGrid',
        'MyForm1',
        'SocialAccountEdit',
        'SocialPlanGrid',
        'SocialItemGridPanel',
        'SocialAccountItemEdit',
        'SearchPerson'
    ],
    controllers: [
        'DateUtil'
    ],
    name: 'sion.salary.social',

    launch: function() {
        Ext.create('sion.salary.social.view.PersonAccountGrid', {renderTo: Ext.getBody()});
    }

});
