/*
 * File: app/view/TaxGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.tax.view.TaxGrid', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action',
        'Ext.grid.View'
    ],

    height: '',
    layout: 'fit',
    title: '个税设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '新建',
                            listeners: {
                                click: {
                                    fn: me.onAddTaxClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    header: false,
                    title: 'Tax ',
                    store: 'TaxStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: '40%',
                            dataIndex: 'name',
                            text: '名称'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: '40%',
                            dataIndex: 'threshold',
                            text: '个税起征点'
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 35,
                            items: [
                                {
                                    iconCls: 's_icon_page_edit',
                                    tooltip: '编辑'
                                }
                            ]
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 35,
                            items: [
                                {
                                    iconCls: 's_icon_cross',
                                    tooltip: '删除'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onAddTaxClick: function(button, e, eOpts) {
        var me=this,
            namespace=me.getNamespace();
        Ext.create(namespace+".view.Tax_win").show();
    }

});