/*
 * File: app/view/TaxItem.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.tax.view.TaxItem', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.XTemplate'
    ],

    height: 250,
    width: 400,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    width: 70,
                                    text: '保存',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'start',
                            fieldLabel: '区段开始值',
                            name: 'start',
                            readOnly: true,
                            allowBlank: false,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'end',
                            beforeLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="">*</span>'
                            ],
                            fieldLabel: '区段结束值',
                            name: 'end',
                            allowBlank: false,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'rate',
                            beforeLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="">*</span>'
                            ],
                            fieldLabel: '税率',
                            name: 'rate',
                            allowBlank: false,
                            decimalPrecision: 0,
                            minValue: 0,
                            listeners: {
                                change: {
                                    fn: me.onRateChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'fastNumber',
                            fieldLabel: '速算扣除数',
                            name: 'fastNumber',
                            readOnly: true,
                            allowBlank: false,
                            minValue: 0
                        }
                    ]
                }
            ],
            listeners: {
                beforerender: {
                    fn: me.onWindowBeforeRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var me = this,
            namespace = me.getNamespace(),
            uuid = Ext.create('Ext.data.UuidGenerator'),
            store = me._itemStore,
            id = uuid.generate(),
            form = me.down("form"),
            lastRecord = null, //上一级对象
            item = me._taxItem,
            store = me._itemStore;

        record = form.getRecord();
        form.updateRecord(record);
        if(!me.down('#start').isValid() || !me.down('#end').isValid() ||
           !me.down('#rate').isValid() || !me.down('#fastNumber').isValid()){
            Ext.Msg.alert("提示", "信息不完整，请继续填写！");
            return false;
        }
        if(item){
            //修改
            if(store.getCount() > 1){
                if(store.indexOf(record) > 0){
                    lastRecord = store.getAt(store.indexOf(record) - 1);
                }
            }
        }else{
            //新增
            if(store.getCount() > 0){
                lastRecord = store.last();
            }
        }
        if(lastRecord !== null){
            if(lastRecord.get('rate') >= record.get('rate')){
                Ext.Msg.alert("提示", "税率应大于上一级的税率" + lastRecord.get('rate'));
                return false;
            }
        }

        if(record.get('id') === ''){
            record.set('id', id);
            store.add(record);
        }else{
            if(store.getCount() > 1){
                for(var i = 1; i < store.getCount(); i++){
                    var prev = store.getAt(i - 1);
                    var current = store.getAt(i);
                    var fastNumber = me.countFastNumber(prev.get('end'), prev.get('rate'), prev.get('fastNumber'), current.get('rate'));
                    current.set('fastNumber', fastNumber);
                }
            }
        }
        me.close();
    },

    onRateChange: function(field, newValue, oldValue, eOpts) {
        this.setFastNumber();
    },

    onWindowBeforeRender: function(component, eOpts) {
        var me = this,
            namespace = me.getNamespace(),
            form = me.down("form"),
            store = me._itemStore,
            item = me._taxItem,
            start = 1;

        if(item){
            form.loadRecord(item);
        }else{
            if(store.getCount() > 0){
                prev = store.last();
                start = prev.get('end') + 1;
            }
            form.loadRecord(Ext.create(namespace + '.model.TaxItem', {
                id: '',
                start: start,
                end: 0,
                rate: 0,
                fastNumber: 0
            }));
        }
        me.down('#end').setMinValue(me.down('#start').getValue() + 1);
        var record = form.getRecord();
        if(store.getCount() > 0){
            if(store.indexOf(record) - 1 >= 0){
                me.down('#rate').setMinValue(store.getAt(store.indexOf(record) - 1).get('rate') + 1);
            }else{
                me.down('#rate').setMinValue(0);
            }
        }
    },

    setFastNumber: function() {
        var me = this,
            form = me.down("form"),
            record = form.getRecord(),
            store = me._itemStore,
            lastRecord = null,
            value = 0;

        if(store.getCount() > 0){
            if(store.indexOf(record) == -1){
                lastRecord = store.last();
            }else{
                if(store.indexOf(record) > 0){
                    lastRecord = store.getAt(store.indexOf(record) - 1);
                }
            }
            if(lastRecord !== null){
                value = me.countFastNumber(lastRecord.get('end'), lastRecord.get('rate'), lastRecord.get('fastNumber'), me.down('#rate').getValue());
                me.down('#fastNumber').setValue(value);
            }
        }
    },

    countFastNumber: function(prevEnd, prevRate, prevFastNumber, rate) {
        // var me = this,
        //     form = me.down("form"),
        //     record = form.getRecord(),
        //     store = me._itemStore,
        //     lastRecord = null,
        var    value = 0;

        // if(store.getCount() > 0){
        //     Number.prototype.mul = function (arg){
        //         return me.accMul(arg, this);
        //     };
        //     Number.prototype.add = function (arg){
        //         return me.accAdd(arg, this);
        //     };
        //     Number.prototype.sub = function (arg){
        //         return me.accSub(arg, this);
        //     };

        //     if(store.indexOf(record) == -1){
        //         lastRecord = store.last();
        //     }else{
        //         if(store.indexOf(record) > 0){
        //             lastRecord = store.getAt(store.indexOf(record) - 1);
        //         }
        //     }
        //     if(lastRecord !== null){
        //         value = (lastRecord.get('end')).mul((me.down('#rate').getValue()).sub(lastRecord.get('rate'))).add(lastRecord.get('fastNumber'));
                value = prevEnd * (rate - prevRate) ;
        //         value = (lastRecord.get('end').mul(lastRecord.get('rate').sub(me.down('#rate').getValue()))).add(lastRecord.get('fastNumber'));
                value = (value * 0.01).toFixed(2);
        //         value = (value).add(lastRecord.get('fastNumber'));
                value = parseFloat(value) + parseFloat(prevFastNumber);
                return value;
        //     }
        // }
    },

    accMul: function(arg1, arg2) {
        // var m = 0, s1 = arg1.toString(), s2 = arg2.toString();
        // try{
        //     m += s1.split(".")[1].length;
        // }catch(e){

        // }
        // try{
        //     m += s2.split(".")[1].length;
        // }catch(e){

        // }
        // return Number(s1.replace(".", "")) * Number(s2.replace(".", "")) / Math.pow(10, m);
    },

    accAdd: function(arg1, arg2) {
        // var r1, r2, m;
        // try{
        //     r1 = arg1.toString().split(".")[1].length;
        // }catch(e){
        //     r1 = 0;
        // }
        // try{
        //     r2 = arg2.toString().split(".")[1].length;
        // }catch(e){
        //     r2 = 0;
        // }
        // m = Math.pow(10, Math.max(r1, r2)) ;
        // return (arg1 * m + arg2 * m) / m ;
    },

    accSub: function(arg1, arg2) {
        //  var r1, r2, m, n;
        //      try{
        //          r1 = arg1.toString().split(".")[1].length;
        //      }catch(e){
        //          r1 = 0;
        //      }
        //      try{
        //          r2 = arg2.toString().split(".")[1].length;
        //      }catch(e){
        //          r2 = 0;
        //      }
        //      m = Math.pow(10, Math.max(r1, r2));
        //      //last modify by deeka
        //      //动态控制精度长度
        //      n = (r1 >= r2) ? r1 : r2;
        //      return ((arg1 * m - arg2 * m) / m).toFixed( n );
    }

});