/*
 * File: app/store/PaymentType.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.store.PaymentType', {
    extend: 'Ext.data.Store',

    requires: [
        'sion.salary.social.model.PaymentType'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'sion.salary.social.model.PaymentType',
            storeId: 'PaymentType',
            data: [
                {
                    id: 'Percent',
                    name: '百分比'
                },
                {
                    id: 'Quota',
                    name: '定额'
                }
            ]
        }, cfg)]);
    }
});