/*
 * File: app/store/PersonStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.payroll.store.PersonStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'sion.salary.payroll.model.Person',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'sion.salary.payroll.model.Person',
            storeId: 'PersonStore',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'salary/payroll/getAccountPersons'
                },
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});