/*
 * File: app/store/TaxItemStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.tax.store.TaxItemStore', {
    extend: 'Ext.data.Store',

    requires: [
        'sion.salary.tax.model.TaxItem',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'sion.salary.tax.model.TaxItem',
            storeId: 'TaxItemStore',
            data: [
                {
                    start: 310,
                    end: 532,
                    rate: 748,
                    fastNumber: 390
                },
                {
                    start: 286,
                    end: 718,
                    rate: 811,
                    fastNumber: 673
                },
                {
                    start: 847,
                    end: 580,
                    rate: 72,
                    fastNumber: 468
                },
                {
                    start: 445,
                    end: 454,
                    rate: 332,
                    fastNumber: 910
                },
                {
                    start: 832,
                    end: 878,
                    rate: 940,
                    fastNumber: 918
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});