/*
 * File: app/store/TaxStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.tax.store.TaxStore', {
    extend: 'Ext.data.Store',

    requires: [
        'sion.salary.tax.model.Tax',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'sion.salary.tax.model.Tax',
            storeId: 'TaxStore',
            data: [
                {
                    name: 'facere',
                    threshold: 515,
                    taxItems: 'neque'
                },
                {
                    name: 'iure',
                    threshold: 514,
                    taxItems: 'ipsum'
                },
                {
                    name: 'illo',
                    threshold: 171,
                    taxItems: 'sit'
                },
                {
                    name: 'eveniet',
                    threshold: 275,
                    taxItems: 'blanditiis'
                },
                {
                    name: 'et',
                    threshold: 469,
                    taxItems: 'officiis'
                },
                {
                    name: 'et',
                    threshold: 355,
                    taxItems: 'eum'
                },
                {
                    name: 'voluptatem',
                    threshold: 585,
                    taxItems: 'velit'
                },
                {
                    name: 'aperiam',
                    threshold: 992,
                    taxItems: 'sapiente'
                },
                {
                    name: 'facere',
                    threshold: 776,
                    taxItems: 'voluptatem'
                },
                {
                    name: 'inventore',
                    threshold: 97,
                    taxItems: 'corrupti'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});