/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    paths: {
        'sion.salary.accounts': 'sion/salary/accounts/app'
    },
    models: [
        'Account',
        'AccountMember',
        'SalaryItem',
        'AccountItem'
    ],
    stores: [
        'SalaryItem',
        'AccountItem',
        'Account',
        'AccountMember'
    ],
    views: [
        'SalaryPlanGrid',
        'SalaryItems',
        'SalaryItemGrid',
        'SalaryPlan',
        'SalaryItemEdit',
        'AddSalaryItem',
        'AccountMember',
        'AccountMemberConfig',
        'SalaryItemRead'
    ],
    name: 'sion.salary.accounts',

    launch: function() {
        Ext.create('sion.salary.accounts.view.SalaryPlanGrid', {renderTo: Ext.getBody()});
    }

});
