/*
 * File: app/store/AccountStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.accounts.store.AccountStore', {
    extend: 'Ext.data.Store',

    requires: [
        'sion.salary.accounts.model.Account',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'sion.salary.accounts.model.Account',
            storeId: 'AccountStore',
            data: [
                {
                    name: 'et',
                    enableLevel: true,
                    accountItems: 'debitis',
                    persons: 'porro'
                },
                {
                    name: 'voluptatem',
                    enableLevel: true,
                    accountItems: 'ipsam',
                    persons: 'voluptatem'
                },
                {
                    name: 'aut',
                    enableLevel: false,
                    accountItems: 'amet',
                    persons: 'velit'
                },
                {
                    name: 'et',
                    enableLevel: true,
                    accountItems: 'sapiente',
                    persons: 'sed'
                },
                {
                    name: 'debitis',
                    enableLevel: true,
                    accountItems: 'incidunt',
                    persons: 'voluptas'
                },
                {
                    name: 'esse',
                    enableLevel: true,
                    accountItems: 'et',
                    persons: 'asperiores'
                },
                {
                    name: 'deserunt',
                    enableLevel: true,
                    accountItems: 'magni',
                    persons: 'laudantium'
                },
                {
                    name: 'veritatis',
                    enableLevel: true,
                    accountItems: 'et',
                    persons: 'blanditiis'
                },
                {
                    name: 'itaque',
                    enableLevel: true,
                    accountItems: 'laborum',
                    persons: 'perferendis'
                },
                {
                    name: 'consequuntur',
                    enableLevel: true,
                    accountItems: 'nostrum',
                    persons: 'minus'
                },
                {
                    name: 'consequatur',
                    enableLevel: true,
                    accountItems: 'voluptate',
                    persons: 'quae'
                },
                {
                    name: 'unde',
                    enableLevel: false,
                    accountItems: 'et',
                    persons: 'in'
                },
                {
                    name: 'mollitia',
                    enableLevel: false,
                    accountItems: 'enim',
                    persons: 'architecto'
                },
                {
                    name: 'et',
                    enableLevel: true,
                    accountItems: 'eum',
                    persons: 'quaerat'
                },
                {
                    name: 'deserunt',
                    enableLevel: false,
                    accountItems: 'repellendus',
                    persons: 'dolor'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});