/*
 * File: app/view/AccountMember_win.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.accounts.view.AccountMember_win', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    height: 540,
    width: 760,
    layout: 'fit',
    title: '方案成员',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '添加',
                            listeners: {
                                click: {
                                    fn: me.onAddClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    header: false,
                    title: 'My Grid Panel',
                    store: 'AccountMemberStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: '20%',
                            dataIndex: 'employeeCode',
                            text: '员工编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: '25%',
                            dataIndex: 'employeeName',
                            text: '员工姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: '25%',
                            dataIndex: 'roleStatus',
                            text: '岗位状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'type',
                            text: '员工类型'
                        },
                        {
                            xtype: 'actioncolumn',
                            width: '10%',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        Ext.create("sion.salary.accounts.view.AccountMemberConfig_win").show();
                                    },
                                    iconCls: 's_icon_coins',
                                    tooltip: '薪资设定'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onAddClick: function(button, e, eOpts) {
        Ext.create("sion.salary.accounts.view.AccountMemberConfig_win").show();
    }

});