/*
 * File: app/view/AddSalaryItem_win.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.accounts.view.AddSalaryItem_win', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea'
    ],

    height: 320,
    width: 480,
    title: '新增套帐项目',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '确定'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '类型',
                            store: [
                                '输入项',
                                '计算项',
                                '系统提取项'
                            ]
                        },
                        {
                            xtype: 'triggerfield',
                            anchor: '100%',
                            fieldLabel: '套帐项目'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            hideEmptyLabel: false,
                            boxLabel: '在薪资报表中显示'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: '值'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});