/*
 * File: app/view/SalaryItemGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.accounts.view.SalaryItemGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.salaryitemgrid',

    requires: [
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Action',
        'Ext.grid.View'
    ],

    header: false,
    title: 'My Grid Panel',
    store: 'SalaryItemStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: '20%',
                    dataIndex: 'name',
                    text: '项目名称'
                },
                {
                    xtype: 'gridcolumn',
                    width: '10%',
                    dataIndex: 'field',
                    text: '字段'
                },
                {
                    xtype: 'gridcolumn',
                    width: '10%',
                    dataIndex: 'type',
                    text: '类型'
                },
                {
                    xtype: 'gridcolumn',
                    width: '30%',
                    dataIndex: 'desc',
                    text: '说明'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'system',
                    text: '系统项'
                },
                {
                    xtype: 'actioncolumn',
                    width: 35,
                    items: [
                        {
                            iconCls: 's_icon_page_edit',
                            tooltip: '编辑'
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    width: 35,
                    items: [
                        {
                            iconCls: 's_icon_cross',
                            tooltip: '删除'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});