/*
 * File: app/view/testDynamicGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.accounts.view.testDynamicGrid', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    height: 250,
    width: 400,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    title: 'My Grid Panel',
                    columns: [
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ]
                }
            ],
            listeners: {
                beforerender: {
                    fn: me.onWindowBeforeRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onWindowBeforeRender: function(component, eOpts) {
        //     fields = [{'name': 'a', 'type': 'String'},{'name': 'b', 'type': 'String'},{'name': 'c', 'type': 'String'}],
        //     columns = [{'header': '编号a', 'dataIndex': 'a'}, {'header': '编号b', 'dataIndex': 'b'}, {'header': '编号c', 'dataIndex': 'c'}],
        //     data = [{'a':'张三', 'b':'1981年', 'c':'男'},{'a':'赵四', 'b':'1984年', 'c':'女'}],
        var me = this,
            grid = me.down('grid'),
            store = Ext.getStore('Dynamic');

        Ext.Ajax.request({
            url:'salary/payroll/memberList',
            method:'post',
            async: true,
            success:function (response){
                json = Ext.JSON.decode(response.responseText);
                store.model.setFields(json.data.fields, null, null);
                store.add(json.data.data);
                grid.reconfigure(store, json.data.columns);
            },failure: function(){
                Ext.Msg.alert("提示", "加载失败");
            }
        });
    }

});