// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.sion.company.salary.domain;

import net.sion.company.salary.domain.PayrollSub;
import org.springframework.data.annotation.Persistent;

privileged aspect PayrollSub_Roo_Mongo_Entity {
    
    declare @type: PayrollSub: @Persistent;
    
}
