/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({

    requires: [
        'formula.jqueryTerminal.terminal'
    ],
    paths: {
        'sion.salary.formula': 'sion/salary/formula/app',
        'formula.jqueryTerminal': 'sion/salary/formula/jqueryTerminal'
    },
    views: [
        'Main',
        'FormulaWin',
        'Screen',
        'CalcButton'
    ],
    controllers: [
        'FormulaController'
    ],
    name: 'sion.salary.formula',

    launch: function() {
        Ext.util.CSS.swapStyleSheet('formula-base','sion/salary/formula/resources/formula.css');
        Ext.util.CSS.swapStyleSheet('formula-terminal','sion/salary/formula/jqueryTerminal/terminal.css');
        Ext.util.CSS.swapStyleSheet('formula-terminal-base','sion/salary/formula/jqueryTerminal/style.css');
        var me = this,
            ns = me.getNamespace();
        var win = Ext.create(ns + '.view.FormulaWin');
        win.show();
    }

});
