/*
 * File: app/controller/FormulaController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.formula.controller.FormulaController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'Screen',
            selector: '#Calc_Screen'
        },
        {
            ref: 'ItemSelection',
            selector: '#Calc_ItemSelection'
        }
    ],

    addInputScreen: function(value, type) {
        /*
        var me = this,
            screen = me.getScreen(),
            displayField = Ext.create('Ext.form.field.Display',{
                value : value,
                _type : type,
                fieldLabel : '',
                fieldStyle : 'font-family:consolas;font-size:50px;line-height:30px;margin-bottom:0px;background:none;color:#FFFFFF;text-shadow: rgb(0, 0, 0) 1px 1px 0px;'

            }),
            inputPanel = screen.down('#inputPanel');


        if (inputPanel._clear) {
            inputPanel.removeAll();
            inputPanel._clear = false;
        }
        inputPanel.add(displayField);
        */
        var me = this,
            term = $('#term_demo').terminal();
        term.insert(value);
        term.focus(true);

    },

    addOutputScreen: function(text, type) {
        var me = this,
            screen = me.getScreen(),
            inputPanel = screen.down('#inputPanel'),
            outputPanel = screen.down('#outputPanel'),
            outputField = Ext.create('Ext.form.field.Display',{
                value : text,
                _type : type,
                fieldLabel : '',
                fieldStyle : 'color:#FFF;'

            }),
            outputFields = outputPanel.query('displayfield')||[],
            displayFields = inputPanel.query('displayfield')||[],
            outputVal = outputField.getValue(),
            inputVal = me.getInputScreenValue(),
            inputField = Ext.create('Ext.form.field.Display',{
                value : inputVal,
                _type : 'Numberic',
                fieldLabel : '',
                fieldStyle : 'color:#FFF;'

            });

        displayFields = inputPanel.query('displayfield');



        if (type == 'Operation') {
           if (outputFields.length>0) {
               if (inputPanel._clear == true&&outputFields[outputFields.length-1]&&outputFields[outputFields.length-1]._type=='Operation') {
                    outputPanel.remove(outputFields[outputFields.length-1]);
               }else {
                   outputPanel.add(inputField);
               }
            }else {
                outputPanel.add(inputField);
            }


            inputPanel._clear = true;
        }

        outputPanel.add(outputField);
    },

    clear: function() {
        var me = this,
            screen = me.getScreen(),
            inputPanel = screen.down('#inputPanel');


        me.addInputScreen(0);
        inputPanel._clear = true;
    },

    clearAll: function() {
        var me = this,
            screen = me.getScreen(),
            inputPanel = screen.down('#inputPanel'),
            outputPanel = screen.down('#outputPanel');

        outputPanel.removeAll();
        me.addInputScreen(0);
        inputPanel._clear = true;
    },

    back: function() {
        var me = this,
            screen = me.getScreen(),
            inputPanel = screen.down('#inputPanel'),
            displayFields = inputPanel.query('displayfield')||[];

        Ext.Array.each(displayFields,function(displayField,index){
            if (index == displayFields.length-1) {
                inputPanel.remove(displayField);
            }
        });
    },

    getInputScreenValue: function() {
        var me = this,
            screen = me.getScreen(),
            inputPanel = screen.down('#inputPanel'),
            displayFields = inputPanel.query('displayfield')||[],
            inputVal = '';

        Ext.Array.each(displayFields,function(displayField,index){
            inputVal += displayField.getValue();

        });

        return parseFloat(inputVal)||inputVal;
    }

});
