/*
 * File: app/controller/Validate.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.formula.controller.Validate', {
    extend: 'Ext.app.Controller',

    containsEqual: function() {

    },

    validate: function(str,array) {
        var message;
        for (var i=0;i<array.length;i++) {
            str = str.replace('[' + array[i] + ']','(' + Math.random()*100 + ')');
        }
        try {
            eval(str);
        }catch (e) {
            message = e.message.replace("Unexpected token ","错误字符 '") + "'";
        }

        return message;
    },

    getTerm: function() {
        var me = this,
            term = $('#term_demo').terminal();

        return term;
    },

    getCommand: function() {
        var me = this,
            term = me.getTerm();

        return term.get_command();
    },

    patch: function(re,s) {
        re=eval("/"+re+"/ig");	//不区分大小写，如须则去掉i,改为 re=eval("/"+re+"/g")
        return s.match(re).length;
    },

    cute: function(str, array) {
        var surfixStr = "";
        if (str.indexOf('[')!=-1) {
            var index = str.indexOf('[');
            str = str.substring(index+1,str.length);

            if (str.indexOf(']')!=-1) {
                var itemName = str.substring(0,str.indexOf(']'));
                array.push(itemName);
                str = str.substring(str.indexOf(']')+1,str.length);
                cute(str,array);

            }else {
                console.log("缺少']'");
            }
        }
    }

});
