/*
 * File: app/view/DocumentForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.view.DocumentForm', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Spacer',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.field.TextArea',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox'
    ],

    height: 766,
    width: 861,
    layout: 'column',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 's_icon_page_add',
                            text: '保存信息'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    columnWidth: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: 'column',
                            bodyPadding: 10,
                            title: '基本信息',
                            items: [
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '员工编号',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '姓名',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '部门',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '职务',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '身份证号',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '工资卡号',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '银行',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '开户网点',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '薪资方案',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '薪资层次',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '薪资级别',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                },
                                {
                                    xtype: 'gridpanel',
                                    columnWidth: 1,
                                    header: false,
                                    title: 'My Grid Panel',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '基本工资'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: '绩效工资'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: '动态列'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: '动态列'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20,
                                    width: 100
                                },
                                {
                                    xtype: 'textareafield',
                                    columnWidth: 1,
                                    margin: '10 0 0 0',
                                    fieldLabel: '备注',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'column',
                            bodyPadding: 10,
                            title: '社保信息',
                            items: [
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '社保号',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '参保日期',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '工作地',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.45,
                                    fieldLabel: '参保状态',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.45,
                                    fieldLabel: '退保日期',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.45,
                                    fieldLabel: '社保方案',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                },
                                {
                                    xtype: 'gridpanel',
                                    columnWidth: 1,
                                    header: false,
                                    title: 'My Tab',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '项目名称',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '基数',
                                            flex: 0.6
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '单位购买类型',
                                            flex: 1.25
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '单位购买百分比',
                                            flex: 1.7
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '单位购买金额',
                                            flex: 1.25
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '个人购买类型',
                                            flex: 1.25
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '个人购买百分比',
                                            flex: 1.7
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '个人购买金额',
                                            flex: 1.25
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                },
                                {
                                    xtype: 'checkboxfield',
                                    columnWidth: 0.15,
                                    fieldLabel: '社保代付地',
                                    labelWidth: 80
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.295,
                                    padding: '0 0 0 10'
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 0.1,
                                    height: 20
                                },
                                {
                                    xtype: 'checkboxfield',
                                    columnWidth: 0.15,
                                    fieldLabel: '公积金代付地',
                                    labelWidth: 90
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.295,
                                    padding: '0 0 0 10'
                                },
                                {
                                    xtype: 'tbspacer',
                                    columnWidth: 1,
                                    height: 20
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});