/*
 * File: app/view/InsuredForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.view.InsuredForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.toolbar.Spacer',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date'
    ],

    height: 621,
    width: 861,
    layout: 'column',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 's_icon_page_add',
                            text: '保存投保信息'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    layout: 'column',
                    title: '基本信息',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '姓名',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 0.1,
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '身份证号',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '社保号',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 0.1,
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '参保日期',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '工作地',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 0.1,
                            height: 20
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.45,
                            fieldLabel: '参保状态',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '退保日期',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 0.1,
                            height: 20
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.45,
                            fieldLabel: '套账信息',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'gridpanel',
                            columnWidth: 1,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '项目名称',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '基数',
                                    flex: 0.6
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '单位购买类型',
                                    flex: 1.25
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '单位购买百分比',
                                    flex: 1.7
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '单位购买金额',
                                    flex: 1.25
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '个人购买类型',
                                    flex: 1.25
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '个人购买百分比',
                                    flex: 1.7
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '个人购买金额',
                                    flex: 1.25
                                }
                            ]
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.15,
                            fieldLabel: '社保代付地',
                            labelWidth: 80
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.295,
                            padding: '0 0 0 10'
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 0.1,
                            height: 20
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.15,
                            fieldLabel: '公积金代付地',
                            labelWidth: 90
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.295,
                            padding: '0 0 0 10'
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    layout: 'column',
                    title: '其他信息',
                    items: [
                        {
                            xtype: 'textareafield',
                            columnWidth: 1,
                            fieldLabel: '备注',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.45,
                            fieldLabel: '创建人',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 0.1,
                            height: 20
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.45,
                            fieldLabel: '创建日期',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            height: 20
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});