/*
 * File: app/view/SocialInsuredGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.view.SocialInsuredGrid', {
    extend: 'Ext.grid.Panel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    height: 515,
    width: 1006,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'form',
                            height: 39,
                            width: 909,
                            layout: 'column',
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.2,
                                    fieldLabel: '关键字',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.2,
                                    margin: '',
                                    padding: '0 0 0 10'
                                },
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.3,
                                    padding: '0 0 0 10',
                                    fieldLabel: '社保套账',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.2,
                                    padding: '0 0 0 10',
                                    fieldLabel: '社保状态',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'button',
                                    columnWidth: 0.05,
                                    height: 25,
                                    text: '查询'
                                }
                            ]
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '参保人'
                },
                {
                    xtype: 'gridcolumn',
                    text: '身份证号'
                },
                {
                    xtype: 'gridcolumn',
                    text: '部门'
                },
                {
                    xtype: 'gridcolumn',
                    text: '职务'
                },
                {
                    xtype: 'gridcolumn',
                    text: '性别'
                },
                {
                    xtype: 'gridcolumn',
                    text: '员工状态'
                },
                {
                    xtype: 'gridcolumn',
                    text: '社保状态'
                },
                {
                    xtype: 'gridcolumn',
                    text: '社保代付地'
                },
                {
                    xtype: 'gridcolumn',
                    text: '公积金代付地'
                },
                {
                    xtype: 'gridcolumn',
                    text: '社保套账'
                },
                {
                    xtype: 'gridcolumn',
                    text: '合计',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            text: '单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            text: '个人'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});