/*
 * File: app/view/SocialPlanGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.view.SocialPlanGrid', {
    extend: 'Ext.panel.Panel',

    requires: [
        'sion.salary.social.view.SocialAccountGrid',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel'
    ],

    height: 505,
    width: 1005,
    title: '社保方案',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '新建方案',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'socialaccountgrid'
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.create("sion.salary.social.view.SocialAccountForm").show();
    }

});