/*
 * File: app/view/SocialItemForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.social.view.SocialItemForm', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Display',
        'Ext.button.Button'
    ],

    height: 274,
    width: 481,
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: '项目名称'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: '类型'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: '小数位数'
                },
                {
                    xtype: 'radiogroup',
                    fieldLabel: '小数保留方式',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: '四舍五入'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: '直接进位'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: '直接舍去'
                        }
                    ]
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: '温馨提示',
                    labelStyle: 'color:red;',
                    value: '小数保留方式默认为四舍五入方式；如需见分进角，则小数位数选1，保留方式选择直接进位即可。 '
                },
                {
                    xtype: 'button',
                    width: 100,
                    text: '保存'
                }
            ]
        });

        me.callParent(arguments);
    }

});