/*
 * File: app/model/Payroll.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.payroll.model.Payroll', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'subject'
        },
        {
            name: 'month',
            type: 'date'
        },
        {
            name: 'socialCostMonth',
            type: 'date'
        },
        {
            name: 'accountId'
        },
        {
            name: 'createDate'
        },
        {
            name: 'persons'
        },
        {
            name: 'createPersonName'
        },
        {
            name: 'state'
        },
        {
            name: 'createPersonId'
        },
        {
            name: 'accountName'
        }
    ],

    proxy: {
        type: 'ajax',
        api: {
            create: 'salary/payroll/create',
            update: 'salary/payroll/update',
            read: 'salary/payroll/read'
        },
        reader: {
            type: 'json',
            messageProperty: 'message',
            root: 'data'
        }
    }
});