/*
 * File: app/view/PayrollSubGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.payroll.view.PayrollSubGrid', {
    extend: 'Ext.grid.Panel',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.grid.plugin.RowEditing'
    ],

    itemId: 'mainGrid1',
    autoScroll: true,
    emptyText: '无工资条数据',
    store: 'PayrollItem',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string'
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {
                    saveBtnText: '保存',
                    cancelBtnText: '取消',
                    listeners: {
                        edit: {
                            fn: me.onRowEditingEdit11,
                            scope: me
                        },
                        beforeedit: {
                            fn: me.onRowEditingBeforeEdit11,
                            scope: me
                        }
                    }
                })
            ]
        });

        me.callParent(arguments);
    },

    onRowEditingEdit11: function(editor, context, eOpts) {


        var me = this,
            record = context.record;


        me.calculate(record,function(values){
            for (var key in values) {
                record.set(key,values[key]);
            }
        });

    },

    onRowEditingBeforeEdit11: function(editor, context, eOpts) {
        var me = this;
        return me._canEdit;

    }

});