/*
 * File: app/view/PayrollMainForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.salary.payroll.view.PayrollMainForm', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    autoShow: true,
    height: 604,
    width: 983,
    layout: 'border',
    title: '薪资发放',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    autoShow: true,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: 'border',
                            title: '创建薪资',
                            listeners: {
                                beforeactivate: {
                                    fn: me.onPanelBeforeActivate,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            height: 527,
                            layout: 'border',
                            title: '待发薪资',
                            listeners: {
                                beforeactivate: {
                                    fn: me.onPanelBeforeActivate1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            layout: 'border',
                            title: '已发薪资'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onPanelBeforeActivate: function(component, eOpts) {
        var me = this,
            store = me.down('#PayrollForm').down('combobox').getStore();
        store.load();
    },

    onPanelBeforeActivate1: function(component, eOpts) {
        var me = this,
            store = me.down('#PayrollGrid').getStore();
        store.load({
            params:{
                state:'Unpublish',
                start:'0',
                page:'1'
            }
        });
    }

});